"""add_owner_id_to_todos

Revision ID: 6e714dc77054
Revises: 7180c244f62f
Create Date: 2026-01-06 02:10:31.297545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e714dc77054'
down_revision: Union[str, None] = '7180c244f62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('owner_id', sa.String(length=255), nullable=False))
    op.create_index('ix_todos_owner_id', 'todos', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_owner_id', table_name='todos')
    op.drop_column('todos', 'owner_id')
    # ### end Alembic commands ###
